### PR TITLE
Models created

### PR DESCRIPTION
**Pull request by Mirvali97**

### CODE REVIEW

**Comment by Mirvali97** [comment]
Aka menimcha ishladi bir kuringchi

**Comment by makhsam** [comment]
@Mirvali97 Baraka topin zo'r chiqibdi! Nimadan bo'ganakan?

**Review by makhsam — APPROVED** [review]
All files are checked. No conficts

**Comment by Mirvali97** [comment]
> @Mirvali97 Baraka topin zo'r chiqibdi! Nimadan bo'ganakan?
Linuxda sudo degan comanda bor men usha bilan clone qilib push qilgan ekanman shunga meni branchimga yangi project bulib tushgan adashmasam

**Pull request merged**
